OWNER_ID = 'destro'
BOT_PREFIX = '(bot)'
TOKEN = 'CxiO1Uov2jQ08W6janJsEtva32FKvAGF'
GAME_CHANNEL = 'lobby'
DEBUG_CHANNEL = 'debug channel '
WEREWOLF_SERVER = 'Loup-Garou'
PLAYERS_ROLE_NAME = 'Players'
ADMINS_ROLE_NAME = 'Admins'
WEREWOLF_NOTIFY_ROLE_NAME = 'Werewolf Notify'
ADMINS = ['admin id', 'admin 2 id', 'etc.']
IGNORE_LIST = []
TOKENS_GIVEN = 5
TOKEN_RESET = 10
IGNORE_THRESHOLD = 7
NOTIFY_FILE = 'notify.txt'
BACKUP_INTERVAL = 300
MESSAGE_LANGUAGE = 'en'
LOG_FILE = 'debug.txt'
MIN_LOG_LEVEL = 1
# 0 to log everything, 1 to log only gameplay-related info, 2 to log only warnings
STASIS_FILE = 'stasis.json'
PLAYING_MESSAGE = '{0}info | {0}help | {0}join'.format(BOT_PREFIX)
